RazorHotelDB21/Pages/Hotels/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB21.Interfaces;
using RazorHotelDB21.Model;
using RazorHotelDB21.Util;

namespace RazorHotelDB21.Pages.Hotels {
    public class CreateModel : PageModel {
        private IAsyncService<Hotel> hotelService;

        [BindProperty(SupportsGet = true)]
        public string Error { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Hotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Address { get; set; }


        public CreateModel(IAsyncService<Hotel> hotelService) {
            this.hotelService = hotelService;
        }

        public void OnGet() {

        }

        public async Task<IActionResult> OnPost() {
            Hotel hotel = new Hotel(Hotel_No, Name, Address);

            Error = await ConstraintHelper.HotelCreateConstraints(hotel, hotelService);
            if (Error != null) {
                return null;
            }

            bool success = await hotelService.CreateItem(hotel);
            if (success) {
                return RedirectToPage("Index");
            } else {
                Error = "Failed to create the hotel";
                return null;
            }
        }
    }
}

RazorHotelDB21/Pages/Hotels/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB21.Interfaces;
using RazorHotelDB21.Model;
using RazorHotelDB21.Util;

namespace RazorHotelDB21.Pages.Hotels {
    public class EditModel : PageModel {

        private Hotel OldHotel {
            get {
                return new Hotel(OldHotel_No, OldName, OldAddress);
            }
            set {
                OldHotel_No = value.Hotel_No;
                OldName = value.Name;
                OldAddress = value.Address;
            }
        }

        private Hotel NewHotel {
            get {
                return new Hotel(NewHotel_No, NewName, NewAddress);
            }
            set {
                NewHotel_No = value.Hotel_No;
                NewName = value.Name;
                NewAddress = value.Address;
            }
        }

        [BindProperty(SupportsGet = true)]
        public int OldHotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public int NewHotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public string OldName { get; set; }
        [BindProperty(SupportsGet = true)]
        public string NewName { get; set; }
        [BindProperty(SupportsGet = true)]
        public string OldAddress { get; set; }
        [BindProperty(SupportsGet = true)]
        public string NewAddress { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Error { get; set; }

        private IAsyncService<Hotel> hotelService;

        public EditModel(IAsyncService<Hotel> hotelService) {
            this.hotelService = hotelService;
        }

        public async Task OnGet(int id) {
            OldHotel = await hotelService.GetItem(new int[] { id });

            NewHotel = OldHotel;
        }

        public async Task<IActionResult> OnPostEdit() {
            Error = await ConstraintHelper.HotelEditConstraints(OldHotel, NewHotel, hotelService);
            if(Error != null) {
                return null;
            }

            bool success = await hotelService.UpdateItem(NewHotel, new int[] { OldHotel.Hotel_No });
            if(success) {
                return RedirectToPage("Index");
            } else {
                Error = "Failed to update the hotel";
                return RedirectToPage("Edit", OldHotel_No);
            }
        }

        public async Task<IActionResult> OnPostDelete() {
            Hotel re = await hotelService.DeleteItem(new int[] { OldHotel.Hotel_No });

            if(re != null) {
                return RedirectToPage("Index");
            } else {
                Error = "Failed to delete the hotel";
                return Page();
            }
        }
    }
}

RazorHotelDB21/Pages/Rooms/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB21.Interfaces;
using RazorHotelDB21.Model;
using RazorHotelDB21.Util;

namespace RazorHotelDB21.Pages.Rooms {
    public class CreateModel : PageModel {
        private IAsyncService<Hotel> hotelService;
        private IAsyncService<Room> roomService;

        [BindProperty(SupportsGet = true)]
        public string Error { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Hotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public int Room_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public RoomTypes Types { get; set; }
        [BindProperty(SupportsGet = true)]
        public double Price { get; set; }

        public CreateModel(IAsyncService<Room> roomService, IAsyncService<Hotel> hotelService) {
            this.roomService = roomService;
            this.hotelService = hotelService;
        }

        public void OnGet(int id) {
            Hotel_No = id;
        }

        public async Task<IActionResult> OnPost() {
            Room room = new Room(Room_No, Hotel_No, Types, Price);

            Error = await ConstraintHelper.RoomCreateConstraints(room, roomService);
            if (Error != null) {
                return null;
            }

            bool success = await roomService.CreateItem(room);
            if (success) {
                return Redirect($"~/Rooms?id={Hotel_No}");
            } else {
                Error = "Failed to create the room";
                return RedirectToPage("Create", Hotel_No);
            }
        }
    }
}

RazorHotelDB21/Pages/Rooms/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB21.Interfaces;
using RazorHotelDB21.Model;
using RazorHotelDB21.Util;

namespace RazorHotelDB21.Pages.Rooms {
    public class EditModel : PageModel {
        private Room OldRoom {
            get {
                return new Room(OldRoom_No, OldHotel_No, OldTypes, OldPrice);
            }
            set {
                OldRoom_No = value.Room_No;
                OldHotel_No = value.Hotel_No;
                OldTypes = value.Types;
                OldPrice = value.Price;
            }
        }

        private Room NewRoom {
            get {
                return new Room(NewRoom_No, NewHotel_No, NewTypes, NewPrice);
            }
            set {
                NewRoom_No = value.Room_No;
                NewHotel_No = value.Hotel_No;
                NewTypes = value.Types;
                NewPrice = value.Price;
            }
        }

        [BindProperty(SupportsGet = true)]
        public int OldRoom_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public int NewRoom_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public int OldHotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public int NewHotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public RoomTypes OldTypes { get; set; }
        [BindProperty(SupportsGet = true)]
        public RoomTypes NewTypes { get; set; }
        [BindProperty(SupportsGet = true)]
        public double OldPrice { get; set; }
        [BindProperty(SupportsGet = true)]
        public double NewPrice { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Error { get; set; }

        private IAsyncService<Room> roomService;

        public EditModel(IAsyncService<Room> roomService) {
            this.roomService = roomService;
        }

        public async Task OnGetAsync(string id) {
            string[] ids = id.Split('-');
            int Room_No = int.Parse(ids[0]);
            int Hotel_No = int.Parse(ids[1]);

            OldRoom = await roomService.GetItem(new int[] { Room_No, Hotel_No });

            NewRoom = OldRoom;
        }

        public async Task<IActionResult> OnPostEdit() {
            Error = await ConstraintHelper.RoomEditConstraints(OldRoom, NewRoom, roomService);
            if (Error != null) {
                return null;
            }

            bool success = await roomService.UpdateItem(NewRoom, new int[] { OldRoom.Room_No, OldRoom.Hotel_No });

            if (success) {
                return Redirect($"~/Rooms?id={OldHotel_No}");
            } else {
                Error = "Failed to update the room";
                return RedirectToPage("Edit", $"{OldRoom.Room_No}-{OldRoom.Hotel_No}");
            }
        }

        public async Task<IActionResult> OnPostDelete() {
            Room re = await roomService.DeleteItem(new int[] { OldRoom.Room_No, OldRoom.Hotel_No });

            if (re != null) {
                return Redirect($"~/Rooms?id={OldHotel_No}");
            } else {
                Error = "Failed to delete the room";
                return RedirectToPage("Edit", $"{OldRoom.Room_No}-{OldRoom.Hotel_No}");
            }
        }
    }
}

RazorHotelDB21/Pages/Rooms/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorHotelDB21.Interfaces;
using RazorHotelDB21.Model;

namespace RazorHotelDB21.Pages.Rooms {
    public class IndexModel : PageModel {
        private IAsyncService<Room> roomService;
        private IAsyncService<Hotel> hotelService;

        [BindProperty(SupportsGet = true)]
        public List<Room> Rooms { get; set; }
        [BindProperty(SupportsGet = true)]
        public int Hotel_No { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Show { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SortBy { get; set; }


        public IndexModel(IAsyncService<Room> roomService, IAsyncService<Hotel> hotelService) {
            this.roomService = roomService;
            this.hotelService = hotelService;
        }

        public async Task OnGet(int id) {
            Hotel_No = id;

            Rooms = await roomService.GetItemsWithKey(1, Hotel_No);

            List<Room> tmp = new List<Room>();
            RoomTypes type = RoomTypes.S;
            bool showAll = true;
            if (Show == "S") {
                showAll = false;
            } else if (Show == "D") {
                type = RoomTypes.D;
                showAll = false;
            } else if (Show == "F") {
                type = RoomTypes.F;
                showAll = false;
            }

            if (!showAll) {
                foreach (Room room in Rooms) {
                    if (room.Types == type) {
                        tmp.Add(room);
                    }
                }
                Rooms = tmp;
            }

            if(SortBy == "Room_No") {
                Rooms.Sort(
                    Comparer<Room>.Create((x,y) => x.Room_No > y.Room_No ? 1 : x.Room_No < y.Room_No ? -1 : 0)
                );
            } else if(SortBy == "Price") {
                Rooms.Sort(
                    Comparer<Room>.Create((x, y) => x.Price > y.Price ? 1 : x.Price < y.Price ? -1 : 0)
                );
            }
        }

        public async Task OnPostSort() {
            await OnGet(Hotel_No);
        }
    }
}

RazorHotelDB21/Pages/Rooms/Create.cshtml
@page
@using RazorHotelDB21.Model;
@model RazorHotelDB21.Pages.Rooms.CreateModel
@{
}

<h1>Create Room</h1>

<h2 class="alert-danger">@Model.Error</h2>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <input type="hidden" asp-for="@Model.Hotel_No" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Room_No" class="custom-control-label"></label>
                <input asp-for="@Model.Room_No" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Types" class="custom-control-label"></label>
                <select asp-for="@Model.Types" class="form-control">
                    <option value="@RoomTypes.S">Single</option>
                    <option value="@RoomTypes.D">Double</option>
                    <option value="@RoomTypes.F">Familie</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Price" class="custom-control-label"></label>
                <input asp-for="@Model.Price" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="create" class="btn btn-primary" />
            </div>
            <div>
                <a asp-page="Index" asp-route-id="@Model.Hotel_No">Back to list</a>
            </div>
        </form>
    </div>
</div>

RazorHotelDB21/Pages/Rooms/Edit.cshtml
@page
@using RazorHotelDB21.Model;
@model RazorHotelDB21.Pages.Rooms.EditModel
@{
}

<h1>Edit Hotel</h1>

<h2>Old Values</h2>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="@Model.OldRoom_No" class="custom-control-label"></label>
            <h5>@Model.OldRoom_No</h5>

        </div>
        <div class="form-group">
            <label asp-for="@Model.OldHotel_No" class="custom-control-label"></label>
            <h5>@Model.OldHotel_No</h5>

        </div>
        <div class="form-group">
            <label asp-for="@Model.OldTypes" class="custom-control-label"></label>
            <h5>@Model.OldTypes</h5>

        </div>
        <div class="form-group">
            <label asp-for="@Model.OldPrice" class="custom-control-label"></label>
            <h5>@Model.OldPrice</h5>

        </div>
    </div>
</div>


<h1 class="alert-danger">@Model.Error</h1>

<h2>New Values</h2>

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="Edit">
            <div class="form-group">
                <label asp-for="@Model.NewRoom_No" class="custom-control-label"></label>
                <input asp-for="@Model.NewRoom_No" class="form-control" />
                <input asp-for="@Model.OldRoom_No" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.NewHotel_No" class="custom-control-label"></label>
                <input asp-for="@Model.NewHotel_No" class="form-control" />
                <input asp-for="@Model.OldHotel_No" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.NewTypes" class="custom-control-label"></label>
                <select asp-for="@Model.NewTypes" class="form-control">
                    <option value="@RoomTypes.S">Single</option>
                    <option value="@RoomTypes.D">Double</option>
                    <option value="@RoomTypes.F">Familie</option>
                </select>
                <input asp-for="@Model.OldTypes" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.NewPrice" class="custom-control-label"></label>
                <input asp-for="@Model.NewPrice" class="form-control" />
                <input asp-for="@Model.OldPrice" type="hidden" />
            </div>
            <div class="form-group">
                <input type="submit" value="edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<form method="post" asp-page-handler="Delete">
    <div class="form-group">
        <input asp-for="@Model.OldRoom_No" type="hidden" />
    </div>
    <div class="form-group">
        <input asp-for="@Model.OldHotel_No" type="hidden" />
    </div>
    <div class="form-group">
        <input asp-for="@Model.OldTypes" type="hidden" />
    </div>
    <div class="form-group">
        <input asp-for="@Model.OldPrice" type="hidden" />
    </div>
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
    </div>
</form>

<div>
    <a asp-page="Index">Back to list</a>
</div>

RazorHotelDB21/Pages/Rooms/Index.cshtml
@page
@using RazorHotelDB21.Model;
@model RazorHotelDB21.Pages.Rooms.IndexModel
@{
}

<p>
    <a asp-page="/Hotels/Index">Back to hotels</a>
</p>

<p>
    <a asp-page="/Rooms/Create" asp-route-id="@Model.Hotel_No">Create new room</a>
</p>

<form method="post" asp-page-handler="Sort">
    <input asp-for="@Model.Hotel_No" type="hidden" />

    <label>Filter by room type</label>
    <select asp-for="@Model.Show" class="form-control">
        <option value="">All</option>
        <option value="S">Single rooms</option>
        <option value="D">Double rooms</option>
        <option value="F">Familie rooms</option>
    </select>

    <label>Sort by</label>
    <select asp-for="@Model.SortBy" class="form-control">
        <option value="Room_No">Room number</option>
        <option value="Price">Price</option>
    </select>
    <div class="form-group">
        <input type="submit" value="Sort" class="btn btn-danger" />
    </div>
</form>

<h4 style="color:aquamarine"> List of rooms for @Model.Name</h4>

<table class="table">
    <thead>
        <tr>
            <th>
                Room No
            </th>
            <th>
                Type
            </th>
            <th>
                Price
            </th>

        </tr>
    </thead>
    <tbody>
        @if (Model.Rooms.Count() != 0) {
            @foreach (var item in Model.Rooms) {
                <tr>
                    <td>
                        @item.Room_No
                    </td>
                    <td>
                        @item.Types.ToString()
                    </td>
                    <td>
                        @item.Price
                    </td>
                    <td>
                        <p>
                            <a asp-page="/Rooms/Edit" asp-route-id="@(item.Room_No + "-" + item.Hotel_No)">Edit</a>
                        </p>
                    </td>
                </tr>
            }
        }
</table>